Id: Shark007.Icaros
Publisher: Shark007
Author: Xanashi
Name: Icaros
AppMoniker: Icaros
Version: 3.1.0
License: Freeware
Homepage: https://www.videohelp.com/software/Icaros
MinOSVersion: 10.0.0.0
Description: Icaros can provide Windows Explorer thumbnails, for essentially any video media format supported by FFmpeg.
Tags: Icaros, Shell Extensions
Installers:
  - Arch: x86
    Url: https://www.videohelp.com/download/Icaros_v3.1.0.exe
    Sha256: 91796f396d7209bcc6f8b95d01ad2417f16bba6c13b74949edaf954e19a9512e
    InstallerType: Inno
    #SystemAppId: Icaros_is1
