PackageIdentifier: Microsoft.DirectXSDK
PackageVersion: 9.29.1962.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://www.microsoft.com/
PackageName: Microsoft DirectX SDK (June 2010)
PackageUrl: https://www.microsoft.com/en-us/download/details.aspx?id=6812
License: Copyright (c) Microsoft Corporation
ShortDescription: Direct X Software Development Kit.
Moniker: directxsdk
Tags:
- directx
- directsound
- directxsdk
ManifestType: defaultLocale
ManifestVersion: 1.0.0
